### ISSUE TITLE
repositories with svn permissions but no git clone

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/bioc_git_transition#12]
Packages with svn permissions in the .authz file but no git repository (e.g., because they were removed from svn at some point, or because the svn authz file is more recent than the snapshot) were created as empty repositories when packages.conf was added. The packages include:

> AffyTiling.git Agi4x44PreProcess.git BeadExplorer.git COPDSexualDimorphism.git ChromoViz.git DASiR.git DAVIDQuery.git DNaseR.git EpiCluster.git GA4GHclient.git GGexplorer.git GeneGroupAnalysis.git GeneR.git GeneRfold.git GeneSpring.git GeneTS.git GeneticsBase.git GenoView.git HTSeqGenieBase.git MMDiff.git RMAGEML.git RMAPPER.git RNASeqGenie.git RTools4TB.git RWebServices.git Rintact.git Rolexa.git STROMA4.git SemSim.git Seqnames.git SomatiCA.git SpliceGraph.git TimerQuant.git arrayMagic.git arrayQCplot.git asmn.git basePLM.git bim.git biocDatasets.git cellHTS.git cosmo.git cosmoGUI.git cydar.git exonmap.git fbat.git flowFlowJo.git flowPhyto.git flowTime.git gene2pathway.git gmapR2.git goCluster.git hdf5.git iFlow.git inSilicoDb.git inSilicoMerging.git jmosaics.git maDB.git makePlatformDesign.git maskBad.git metaX.git mmgmos.git mtbls2.git neaGUI.git netReg.git pairseqsim.git pgUtils.git prism.git spade.git stam.git virtualArray.git wiggleplotr.git xcmsGUI.git xmapcore.git

Either the git repositories should be created from svn (for posterity) or the empty repositories should be removed (and permissions file updated).

**Comment by nturaga** [comment]
Some of these packages are missing because the SVN dump is not updated.
