### ISSUE TITLE
manage https permissions via gitolite

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/bioc_git_transition#15]
Currently, repositories under repositories/packages/ but not repositories/ are accessible because of an https configuration  in Apache. It might be better for Apache to allow access to everything under repositories/, and for gitolite to be responsible for controlling access below that.

**Comment by nturaga** [comment]
This should be fixed with commit b007c61a6021044a84111729fc26e497816e9a3f

**Comment by mtmorgan** [comment]
https:// access is still through apache directly; this issue is really that gitolite should be managing https:// access. The solution requires adjusting the apache configuration.

**Comment by nturaga** [comment]
@mtmorgan You are right. I'll edit to remove commit # there.

**Comment by mtmorgan** [comment]
gitollite now manages permissions.
