### ISSUE TITLE
Error 403: Forbidden

### ISSUE THREAD

**Issue by aoles** [Bioconductor/bioc_git_transition#21]
Attempts to communicate with https://git.bioconductor.org return *Error 403*.

```
$ git clone https://git.bioconductor.org/packages/BiocGenerics.git
Cloning into 'BiocGenerics'...
error: The requested URL returned error: 403 Forbidden while accessing https://git.bioconductor.org/packages/BiocGenerics.git/info/refs?service=git-upload-pack
```

Also opening https://git.bioconductor.org in the web browser gives *403 Forbidden*.

**Comment by mtmorgan** [comment]
Looks like a file permission issue

```
ubuntu@ip-172-30-0-33:/var/log/apache2$ tail error.log
...
[Tue May 23 12:42:10.297170 2017] [core:error] [pid 1158:tid 139630376605440] (13)Permission denied: [client 74.77.3.210:38420] AH00035: access to /packages/BiocGenerics.git/info/refs denied (filesystem path '/home/git/bin/gitolite-suexec-wrapper.sh') because search permissions are missing on a component of the path`
```
I think because the https user ('nobody') is not part of the git group, or because the permissions on the repositories are too restrictive (750 instead of 755). I'm not sure what the correct resolution is @vobencha  ?

**Comment by vobencha** [comment]
Last week permissions on /home/git/bin were changed form 755 to 700 as per request. This is too restrictive and I've changed it back to 755.

FYI I've also did system updates and rebooted this morning.

Val

**Comment by mtmorgan** [comment]
Perfect, thanks, sorry for makin' you change the permissions last week...
