### ISSUE TITLE
Timezone setting of git repositories

### ISSUE THREAD

**Issue by aoles** [Bioconductor/bioc_git_transition#24]
There seem to be some inconsistency in handling timezones in pkg git repos compared to svn. For example, `svn log` on https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/Biobase/ returns
```
r129129 | hpages@fhcrc.org | 2017-04-24 21:50:57 +0200 (Mon, 24 Apr 2017) | 1 line

bump x.y.z versions to odd y after creation of 3_5 branch
```
while `git log` on https://git.bioconductor.org/packages/Biobase gives
```
commit 867db36c18c4738157710dba2f9889459a0002da
Author: Herve Pages <hpages@fhcrc.org>
Date:   Mon Apr 24 19:50:57 2017 +0000

    bump x.y.z versions to odd y after creation of 3_5 branch
    
    git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/Biobase@129129 bc3139a8-67e5-0310-9ffc-ced21a209358
```
It would be good to configure the git server to use the same timezone setting as the builders in order to have consistent date format e.g. in build reports.

**Comment by nturaga** [comment]
There is an option which does that as per `git-svn` but I don't think its worth it, because we use the git-svn interoperability to update the most recent release and master (`trunk`) branches.  The `--convert-timezones` apparently breaks that interoperability. I could give it a test go, but i'll let @mtmorgan decide if he thinks this is worth it. 

Does it break anything in the build reports? Other than having the timezone difference? 

```
--convert-timezones;; 
	Store Git commit times in the local timezone instead of UTC.  This 
	makes 'git-log' (even without --date=local) show the same times 
	that `svn log` would in the local timezone. 
 
This breaks interoperability with SVN, but may be cosmetically 
desirable when converting a repository from SVN to Git. 
```

**Comment by mtmorgan** [comment]
Probably the builds need to do something like `git log --date=local` anyway, because otherwise the commits are presented in the time zone of the committer.

```
mtmorgan@CND5360DSX:/tmp/Rsamtools$ git log |head -n 3
commit d0079c84a0c267759d11f16e7ca9ebc84459c559
Author: Martin Morgan <martin.morgan@roswellpark.org>
Date:   Thu Jun 15 01:54:30 2017 -0400
mtmorgan@CND5360DSX:/tmp/Rsamtools$ git log --date=local |head -n 3
commit d0079c84a0c267759d11f16e7ca9ebc84459c559
Author: Martin Morgan <martin.morgan@roswellpark.org>
Date:   Thu Jun 15 01:54:30 2017
```

So far I think we should NOT convert time zones.

**Comment by nturaga** [comment]
@aoles Let me know if this helps.

**Comment by aoles** [comment]
Thanks @mtmorgan! The `local` setting to `git log` seems helpful. Funny enough, apparently there is a bug in `git log` which prevents me from getting the desired format with the timezone offset field set correctly. Seems to be a relatively fresh thing, so not sure when a version containing a bugfix will be released and available on the builders, see https://public-inbox.org/git/22824.29946.305300.380299@a1i15.kph.uni-mainz.de/#t.

```
> svn co https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/vsn
> cd vsn
> svn info |grep "Last Changed Date"
Last Changed Date: 2017-04-24 15:50:57 -0400 (Mon, 24 Apr 2017)
```
```
> git clone https://git.bioconductor.org/packages/vsn
> cd vsn
>git log --max-count=1 --date=format-local:"%Y-%m-%d %H:%M:%S %z (%a, %d %b %Y)" --format=format:"Last Changed Date: %ad%n"
Last Changed Date: 2017-04-24 15:50:57 +0000 (Mon, 24 Apr 2017)
```
Note the wrong timezone offset `+0000` in the git output.
