### ISSUE TITLE
Manifest repository gone

### ISSUE THREAD

**Issue by aoles** [Bioconductor/bioc_git_transition#26]
The following used to work for me before; cloning of https://git.bioconductor.org/packages/PACKAGENAME.git works.

```
> git clone https://git.bioconductor.org/admin/manifest
Cloning into 'manifest'...
fatal: repository 'https://git.bioconductor.org/admin/manifest.git/' not found
```

**Comment by mtmorgan** [comment]
This seems to be solved by

```
touch ~git/repositories/admin/manifest.git/git-daemon-export-ok
```

(which I did) but @nturaga is this the 'best practice' (adding these files manually to repositories we want exported)? Are these created by 'us' when we make the bare repositories, or is it something git handles?

**Comment by nturaga** [comment]
`gitolite setup` is supposed to do it. I'll take a look at why this didn't happen.
