### ISSUE TITLE
packages with empty (sometimes intentionally) directories

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/bioc_git_transition#35]
e.g., AnnotationForge, BSgenome; mzR? many other empty directories for unknown reasons.

- git doesn't support empty directories
- hack: faux file in the directory, e.g., `.__placeholder__`

**Comment by nturaga** [comment]
Hi @mtmorgan , I do not have a check out of the entire SVN repo, can you try

`find . -type d -empty -print` 

on your packages directory, both software(`/madman/Rpacks`) and data-experiment (`experiment/pkgs`) and let me know what packages have empty folder?

**Comment by mtmorgan** [comment]
sent privately; some are safely ignored, e.g., 

```
$ grep -c "inst$" empty-dirs.txt 
201
$ grep -c "inst/doc$" empty-dirs.txt 
90
```

**Comment by nturaga** [comment]
@hpages resolved this issue.
