### ISSUE TITLE
where should I commit?

### ISSUE THREAD

**Issue by GuangchuangYu** [Bioconductor/bioc_git_transition#37]
The package build fail due to tidyr v0.7.0 upgrade and although I have fixed it and commit to bioc-git. It seems there is no effect for the commit. <https://bioconductor.org/checkResults/devel/bioc-LATEST/ggtree/malbec1-buildsrc.html>. 

Should I need to commit to svn?

**Comment by mtmorgan** [comment]
No, you cannot commit to svn.

The build system behaves the same as before, but are based on git. Builds start nightly at approximately 5pm, with a report, if builds are successful, at about 2pm (US Eastern time) the next day. You can see that the 'snapshot date' on the build page is 2017-08-16 16:10:04 -0400 (Wed, 16 Aug 2017). When did you make the commit that you think fixed the problem?

**Comment by mtmorgan** [comment]
Actually, the build system was not consistently pulling the most recent commit; this will be updated in the next build, hopefully Friday night / Saturday.

**Comment by mtmorgan** [comment]
The builds are pulling from the correct commit now (site_src seems to be in your .svnignore, but at the same time checked in to the svn repo so cloned to git?).

**Comment by GuangchuangYu** [comment]
thanks @mtmorgan. FYI, `site_src` is used to build the homepage and will be ignored (in .Rbuildingore) when building the package.
