### ISSUE TITLE
Fail to push changes on RELEASE_3_9 branch 

### ISSUE THREAD

**Issue by nephantes** [Bioconductor/bioc_git_transition#44]
I get the following error if I try to push to RELEASE_3_9 branch. Pushing to master branch works fine.
![Screen Shot 2019-10-21 at 12 52 54 PM](https://user-images.githubusercontent.com/4869692/67225769-ccd27500-f401-11e9-833f-afaabd2c09dd.png)

**Comment by lshep** [comment]
The RELEASE_3_9 branch was frozen on October 15th as indicated on the [release schedule](
http://bioconductor.org/developers/release-schedule/).

**Comment by lshep** [comment]
This was also announced on the bioc-devel mailing list  and the support site. 
https://support.bioconductor.org/p/125553/
https://stat.ethz.ch/pipermail/bioc-devel/2019-October/015648.html
